### ISSUE TITLE
Burgers 1D Models TODO

### ISSUE THREAD

**Issue by vpuri3** [vpuri3/PDEInterfaces.jl#27]
- [ ] reduce models to simple test-cases with (nsims=2) and test on CPU till https://github.com/jonniedie/ComponentArrays.jl/issues/155 type bugs are sorted
- [ ] verify that encapsulating SciMLOperators update calls in Zygote.ignore() doesn't affect gradient https://github.com/vpuri3/PDEInterfaces.jl/blob/ceb3ab1529cb5f3c30258ae2da5d4b968d6ef97c/examples/burgers/model0.jl#L77-L86
- [ ] eventually have Zygote play nice with `A(u,p,t)` since none of the inputs are modified in the update.
